### ISSUE TITLE
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #3 'index' in call to _th_index_add_

### ISSUE THREAD

**Issue by gethubwy** [uzh-rpg/rpg_e2vid#5]
When I run the code on GPU,I got the error blew:
Traceback (most recent call last):
  File "run_reconstruction.py", line 107, in <module>
    device=device)
  File "/home/wy/rpg_e2vid-master/utils/inference_utils.py", line 533, in events_to_voxel_grid_pytorch
    source=vals_left[valid_indices])
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #3 'index' in call to _th_index_add_
------------------------------------------------------------------------
I find that the code is :
`            voxel_grid.index_add_(dim=0,
                                  index=xs[valid_indices] + ys[valid_indices]
                                  * width + tis_long[valid_indices] * width * height,
                                  source=vals_left[valid_indices])`
--------------------------------------------------------------------------
thanks in advance.

**Comment by supitalp** [comment]
Hello,
Which version of PyTorch are you using? I seem to remember there was a slight API change in PyTorch that caused this issue in older versions.

**Comment by shiba24** [comment]
facing the same error with `torch==1.3.1`

**Comment by saiyaswanth97** [comment]
voxel_grid.index_add_(dim=0,
                                  index=(xs[valid_indices] + ys[valid_indices]
                                  * width + tis_long[valid_indices] * width * height).**long()**,
                                  source=vals_left[valid_indices])

**Comment by vikinglee16** [comment]
I am also facing with the same error with torch==1.4.0

**Comment by supitalp** [comment]
Thanks for the feedback. I don't have access to a machine with a GPU to reproduce this now.
Does the following change fix the error?

```python
voxel_grid.index_add_(
                      dim=0,
                      index=(xs[valid_indices] + ys[valid_indices] * width + tis_long[valid_indices] * width * height).long(),
                      source=vals_left[valid_indices]
)
```

**Comment by saiyaswanth97** [comment]
It runs on jetson tx2 with the change (torch version 1.3.0).

**Comment by shiba24** [comment]
For GPU environment, 

```
            voxel_grid.index_add_(dim=0,
                                  index=(xs[valid_indices] + ys[valid_indices]
                                  * width + tis_long[valid_indices] * width * height).type(torch.cuda.LongTensor),
                                  source=vals_left[valid_indices])
```
should fix this.

**Comment by Tobias-Fischer** [comment]
Also fixed in https://github.com/uzh-rpg/rpg_e2vid/pull/11
